/* eslint-disable react-refresh/only-export-components */
import "@/app/global.scss";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import type { Metadata } from "next";
import {notoSans} from "@/shared/fonts/fonts"
import Layout from "./layout/index";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const isAuth = true
  return (
    <html className={notoSans.className} lang="ru" suppressHydrationWarning>
      <body className="wrapper">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Layout isAuth={isAuth}>{children}</Layout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
