/* eslint-disable react-refresh/only-export-components */
import "@/app/global.scss";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import type { Metadata } from "next";
import {notoSans} from "@/shared/fonts/fonts"
import Layout from "./layout/index";
import { Suspense } from "react";
import SkeletonPage from "@/shared/ui/skeleton/skeletonPage";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: "/public/logo.svg"
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  const isAuth = true
  return (
    <html className={notoSans.className} lang="ru" suppressHydrationWarning>
      <body className="wrapper">
        <Suspense fallback={<SkeletonPage/>}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            <Layout isAuth={isAuth}>{children}</Layout>
          </AppRouterCacheProvider>
        </Suspense>
      </body>
    </html>
  );
}
