/* eslint-disable react-refresh/only-export-components */
import "@/app/global.scss";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import type { Metadata } from "next";
import { notoSans } from "@/shared/fonts/fonts";
import Layout from "./layout/index";
import { Suspense } from "react";
import SkeletonPage from "@/shared/ui/skeleton/skeletonPage";
import { MiniSideBarAudio } from "@/entities/audio";
import { IMiniSideBarAudioProps } from "@/shared/interfaces/audio";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: "/public/logo.svg",
};
const audio:IMiniSideBarAudioProps = {
   audio: {
    image: "/car.png",
    src: "/NLO22 - MYICE Alternate Version.mp3",
    name: "nlo"
   },
   isAudio: true
}
export default function RootLayout({
  children,
  settings,
}: {
  children: React.ReactNode;
  settings: React.ReactNode;
}) {
  const isAuth = true;
  return (
    <html className={notoSans.className} lang="ru" suppressHydrationWarning>
      <body className="wrapper">
        <Suspense fallback={<SkeletonPage />}>
          <AppRouterCacheProvider options={{ enableCssLayer: true }}>
            {/* <MiniSideBarAudio {...audio} /> */}
            {settings}
            <Layout isAuth={isAuth}>{children}</Layout>
          </AppRouterCacheProvider>
        </Suspense>
      </body>
    </html>
  );
}
